### ISSUE TITLE
Include Shannon capacity in the system model

### ISSUE THREAD

**Issue by MartinPJorge** [khasa22/COTORRA#1]
![Captura de pantalla 2022-01-18 a las 19 08 37](https://user-images.githubusercontent.com/3333738/149994063-8eed2375-bf43-4a3b-aea5-79bfcd6ea0fd.png)

The above constraint already imposes that you have to attach to a RSU with a given gain.

Let's derive T using the Shannon capacity theorem. That is, if the service S_i imposes a minimum bandwidth B(S_i), then the transmission gain of the RSU (i.e., T) should be enough to reach such minimum BW according to the Shannon capacity.

**Comment by khasa22** [comment]
I am starting working on it.BTW prevously we are considering (T) as given value kinda set value to which we say it should be greater than given gain. Therefore I will think how we can drive it.

**Comment by khasa22** [comment]
Almost got it .Will encod it in mod file and also update in latex file

**Comment by khasa22** [comment]
Added to in latex file.have a look when you have time

**Comment by MartinPJorge** [comment]
Model done in the LaTeX file.
@khasa22 polish it up!

**Comment by khasa22** [comment]
Updated LaTex file.
